name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: [v1.12.10, v1.14.10, v1.16.9, v1.18.2]

    steps:
    - uses: actions/checkout@v2

    - name: Create Kubernetes ${{ matrix.k8s }} cluster
      id: kind
      uses: engineerd/setup-kind@v0.3.0
      with:
        version: v0.8.1
        config: hack/kubernetes/kind-psp.yaml
        image: kindest/node:${{ matrix.k8s }}

    - name: Prepare cluster for testing
      id: local-path
      run: |
        echo "create standard pod security policies"
        kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/psp/privileged-psp.yaml
        kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/psp/baseline-psp.yaml
        kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/psp/restricted-psp.yaml
        echo "create roles and rolebindings for psp"
        kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/kind/psp/cluster-roles.yaml
        kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/kind/psp/role-bindings.yaml
        echo "waiting for nodes to be ready ..."
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        kubectl get pods --all-namespaces
        sleep 30
        # kubectl wait --for=condition=Ready nodes --all --timeout=5m
        # kubectl get nodes
        echo
        kubectl version --short

    - name: Test pod
      run: |
        kubectl apply -f ./hack/kubernetes/pod.yaml
        sleep 10
        kubectl get pods
        sleep 10
        kubectl get pods
        sleep 10
        kubectl get pods -o yaml
